---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nice-note-ingress
  namespace: noteapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # kubernetes.io/ingress.allow-http: "false"
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.global-static-ip-name: "nice-note-ip"
  labels:
    app: "nice-note"
spec:
  backend:
    serviceName: robin-dot-com-nodeport
    servicePort: 443
  tls:
  - hosts:
    - robinyonge.com
    secretName: robinyonge-dot-com-crt
  rules:
  - host: robinyonge.com
    http:
      paths:
      - path: /webhook
        backend:
          serviceName: nice-note-nodeport
          servicePort: 443
  - host: robinyonge.com
    http:
      paths:
      - path: /
        backend:
          serviceName: robin-dot-com-nodeport
          servicePort: 443